---

- name: restart strongswan
  systemd: name=strongswan state=restarted daemon_reload=yes

- name: restart apparmor
  service: name=apparmor state=restarted

- name: save iptables
  command: service netfilter-persistent save
  tags: skip_ansible_lint

- name: restart iptables
  service: name=netfilter-persistent state=restarted

- name: rereadcrls
  command: ipsec rereadcrls
